spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
      password:
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 100